Fixes docker build error - nodejs-npm upstream package renamed
Fixes following error:

```
23-03-20 09:26:07 INFO (SyncWorker_0) [supervisor.docker.addon] Starting build for 1bf255b3/amd64-addon-ring_alarm:0.52
23-03-20 09:26:11 ERROR (SyncWorker_0) [supervisor.docker.addon] Can't build 1bf255b3/amd64-addon-ring_alarm:0.52: The command '/bin/ash -o pipefail -c apk add --no-cache nodejs-npm git' returned a non-zero code: 1
23-03-20 09:26:11 ERROR (SyncWorker_0) [supervisor.docker.addon] Build log:
Step 1/13 : ARG BUILD_FROM
Step 2/13 : FROM $BUILD_FROM
 ---> eb8315f819a1
Step 3/13 : ENV LANG C.UTF-8
 ---> Running in 2ba705794d1b
Removing intermediate container 2ba705794d1b
 ---> 3578a845a1ba
Step 4/13 : RUN apk add --no-cache nodejs-npm git
 ---> Running in 1fddbe730319
fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/community/x86_64/APKINDEX.tar.gz
ERROR: unable to select packages:

  nodejs-npm (no such package):
    required by: world[nodejs-npm]
Removing intermediate container 1fddbe730319
```